import { NextResponse } from "next/server"
import sgMail from "@sendgrid/mail"

// Configura la API Key de SendGrid.
// process.env.SENDGRID_API_KEY es la variable de entorno que configurarás en Netlify.
if (process.env.SENDGRID_API_KEY) {
  sgMail.setApiKey(process.env.SENDGRID_API_KEY)
}

export async function POST(request: Request) {
  const body = await request.json()
  const { name, email, phone, trailerType, message } = body

  if (!process.env.SENDGRID_API_KEY) {
    console.error("SENDGRID_API_KEY no está configurada")
    return NextResponse.json({ message: "Error de configuración en el servidor." }, { status: 500 })
  }

  const msg = {
    to: "castleautotransport1@gmail.com", // The website owner's email.
    from: "contact@castlestrailerepair.com", // This must be a verified email in SendGrid.
    subject: `New Appointment from Castle's Auto Trailer Repair Services`,
    html: `
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>New Contact Inquiry</title>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; background-color: #f4f7f6; color: #333; margin: 0; padding: 20px; }
          .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 15px rgba(0,0,0,0.1); border: 1px solid #e0e0e0; }
          .header { background-color: #004AAE; color: #ffffff; padding: 30px 20px; text-align: center; }
          .header h1 { margin: 0; font-size: 26px; font-weight: 600; }
          .content { padding: 30px; }
          .content h2 { color: #004AAE; border-bottom: 2px solid #eeeeee; padding-bottom: 10px; font-size: 20px; margin-top: 0; }
          .details-table { width: 100%; margin-bottom: 25px; border-collapse: collapse; }
          .details-table th, .details-table td { padding: 12px 0; text-align: left; vertical-align: top; }
          .details-table th { font-weight: 600; color: #555; width: 30%; }
          .details-table td a { color: #004AAE; text-decoration: none; }
          .message-box { background-color: #f9f9f9; border-left: 4px solid #004AAE; padding: 20px; margin-top: 20px; }
          .message-box p { margin: 0; white-space: pre-wrap; word-wrap: break-word; line-height: 1.6; }
          .footer { background-color: #333333; color: #bbbbbb; text-align: center; padding: 20px; font-size: 12px; }
          .footer p { margin: 0; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>New Website Inquiry</h1>
          </div>
          <div class="content">
            <h2>Contact Details</h2>
            <table class="details-table">
              <tr><th>Name</th><td>${name}</td></tr>
              <tr><th>Email</th><td><a href="mailto:${email}">${email}</a></td></tr>
              <tr><th>Phone</th><td><a href="tel:${phone}">${phone}</a></td></tr>
              <tr><th>Trailer Type</th><td>${trailerType}</td></tr>
            </table>
            <h2>Message</h2>
            <div class="message-box">
              <p>${message}</p>
            </div>
          </div>
          <div class="footer">
            <p>This email was automatically generated by the Castle's Auto Trailer Repair Services website.</p>
          </div>
        </div>
      </body>
      </html>
    `,
  }

  try {
    await sgMail.send(msg)
    return NextResponse.json({ message: "Email enviado exitosamente" }, { status: 200 })
  } catch (error) {
    console.error(error)
    return NextResponse.json({ message: "Error al enviar el email" }, { status: 500 })
  }
}
